name: Feature Request
description: Propose a new feature for Settler OSS
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Before submitting

        - Search existing issues and discussions to avoid duplicates
        - Consider whether this belongs in core OSS or as a plugin/extension
        - Understand that feature requests are not commitments or roadmap items

        **Important:** Feature requests will be evaluated based on alignment with project goals, maintainer capacity, and community benefit. Many feature requests will be declined. This is normal and not personal.

  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: Where should this feature live?
      options:
        - Core SDK (TypeScript/Node.js)
        - Multi-language SDK support
        - CLI tool
        - React components
        - Protocol/Types
        - Documentation
        - Developer experience
        - Not sure
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve? Describe the gap or pain point.
      placeholder: "Currently, users cannot... This causes..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Specific scenario where this feature would be used. Who benefits?
      placeholder: |
        As a [type of user], I need to [do something] so that [outcome].

        Concrete example:
        - User profile: Engineering team at mid-size fintech
        - Frequency: Daily reconciliation workflow
        - Current workaround: Manual scripting that takes 2 hours
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this implemented?
      placeholder: |
        Add a new method/option/feature that allows...

        Example API:
        ```typescript
        client.reconcile({
          source: data,
          // new feature here
        });
        ```

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions or workarounds have you tried or considered?
      placeholder: |
        1. Current workaround: [describe]
           - Limitation: [why this doesn't work well]
        2. Alternative approach: [describe]
           - Trade-off: [why you didn't choose this]
    validations:
      required: true

  - type: dropdown
    id: why-core
    attributes:
      label: Why Core OSS?
      description: Why should this be in the core repository instead of a plugin, external tool, or user-land code?
      options:
        - Requires changes to protocol or SDK internals
        - Common need across many users
        - Improves developer experience significantly
        - Enables new use cases not possible externally
        - Not applicable (external solution acceptable)
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact and Adoption
      description: Who else would benefit from this? How widely applicable is it?
      placeholder: |
        - Target users: [describe]
        - Estimated adoption: [percentage of users who would use this]
        - Validation: [how do you know others need this?]

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Changes
      description: Would this require breaking changes?
      options:
        - No breaking changes needed
        - Minor breaking changes in non-critical paths
        - Major breaking changes required
        - Unknown
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Intent
      description: Are you willing to help implement this?
      options:
        - label: I am willing to submit a PR for this feature
        - label: I can help with testing and feedback
        - label: I can help with documentation
        - label: I am requesting this but cannot contribute code

  - type: checkboxes
    id: understanding
    attributes:
      label: Understanding
      description: Confirm you understand the maintainer policy
      options:
        - label: I understand this is a request, not a demand
          required: true
        - label: I understand maintainers may decline this without detailed justification
          required: true
        - label: I understand "no response" does not mean "rejected" (maintainers have limited time)
          required: true
        - label: I understand feature requests may remain open indefinitely without implementation
          required: true
